if (!sessionStorage.getItem('carnicos_session')) location.replace('index.html');
const defaults=[{id:1,name:'Carne molida',price:18000,stock:20},{id:2,name:'Pechuga de pollo',price:16000,stock:16},{id:3,name:'Costilla de cerdo',price:22000,stock:12},{id:4,name:'Chorizo artesanal',price:14000,stock:25}];
let products=JSON.parse(localStorage.getItem('carnicos_products')||'null')||defaults;let cart=[];
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
const save=()=>localStorage.setItem('carnicos_products',JSON.stringify(products));
function renderProducts(){const q=document.querySelector('#search').value.toLowerCase();document.querySelector('#products').innerHTML=products.filter(p=>p.name.toLowerCase().includes(q)).map(p=>`<article class="product-card"><h3>${p.name}</h3><span class="stock">${p.stock} disponibles</span><span class="price">${money(p.price)}</span><button data-add="${p.id}" ${p.stock<1?'disabled':''}>Agregar</button></article>`).join('')||'<p class="empty">No se encontraron productos.</p>';}
function renderCart(){const box=document.querySelector('#cart-items');box.innerHTML=cart.map(i=>`<div class="cart-row"><div><strong>${i.name}</strong><br><small>${i.qty} × ${money(i.price)}</small></div><button data-remove="${i.id}" aria-label="Quitar">✕</button></div>`).join('')||'<p class="empty">El carrito está vacío.</p>';const total=cart.reduce((s,i)=>s+i.price*i.qty,0);document.querySelector('#cart-total').textContent=money(total);document.querySelector('#checkout').disabled=!cart.length;}
document.querySelector('#products').addEventListener('click',e=>{const id=Number(e.target.dataset.add);if(!id)return;const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id);const reserved=item?.qty||0;if(reserved>=p.stock)return;if(item)item.qty++;else cart.push({...p,qty:1});renderCart();});
document.querySelector('#cart-items').addEventListener('click',e=>{const id=Number(e.target.dataset.remove);if(!id)return;cart=cart.filter(x=>x.id!==id);renderCart();});
document.querySelector('#search').addEventListener('input',renderProducts);
document.querySelector('#product-form').addEventListener('submit',e=>{e.preventDefault();products.push({id:Date.now(),name:document.querySelector('#new-name').value.trim(),price:Number(document.querySelector('#new-price').value),stock:Number(document.querySelector('#new-stock').value)});save();e.target.reset();renderProducts();});
document.querySelector('#checkout').addEventListener('click',()=>{cart.forEach(i=>products.find(p=>p.id===i.id).stock-=i.qty);save();cart=[];renderProducts();renderCart();const m=document.querySelector('#message');m.textContent='Venta registrada correctamente.';setTimeout(()=>m.textContent='',3000);});
document.querySelector('#logout').addEventListener('click',()=>{sessionStorage.removeItem('carnicos_session');location.replace('index.html');});renderProducts();renderCart();
